import { allAttributes, allManyRefs, allSingleRefs, GenClass, GenerationModel } from '../GenerationModel';
import { isAutoGeneratedPk } from '../typeMapping';
import { generatedFileHeader, getterSetter, importLines } from './javaUtil';

// Los Controllers trabajan con DTOs, no con las entidades (seccion 34):
// - La PK se expone siempre como "id". En el RequestDTO solo se incluye si
//   la base no la autogenera (String, fechas...): ahi la manda el cliente.
// - Las referencias a otras clases se aplanan a su id ("clienteId") y las
//   N:M a una lista de ids ("materiasIds"), para no exponer el grafo de
//   entidades completo (evita ciclos JSON, seccion 12).
// - En una subclase, el DTO incluye tambien los campos heredados.

export function renderRequestDto(model: GenerationModel, klass: GenClass): string {
  const imports: string[] = [];
  const fields: string[] = [];
  const accessors: string[] = [];
  let usesNotNull = false;

  const pk = klass.pkAttribute;
  if (!isAutoGeneratedPk(pk.javaType)) {
    if (pk.javaImport) imports.push(pk.javaImport);
    usesNotNull = true;
    fields.push(`    @NotNull\n    private ${pk.javaType} id;`);
    accessors.push(getterSetter(pk.javaType, 'id'));
  }

  for (const attr of allAttributes(klass)) {
    if (attr.javaImport) imports.push(attr.javaImport);
    if (!attr.nullable) usesNotNull = true;
    fields.push(`${attr.nullable ? '' : '    @NotNull\n'}    private ${attr.javaType} ${attr.fieldName};`);
    accessors.push(getterSetter(attr.javaType, attr.fieldName));
  }

  for (const ref of allSingleRefs(klass)) {
    if (ref.referencedPkJavaImport) imports.push(ref.referencedPkJavaImport);
    if (!ref.optional) usesNotNull = true;
    const fieldName = `${ref.fieldName}Id`;
    fields.push(`${ref.optional ? '' : '    @NotNull\n'}    private ${ref.referencedPkJavaType} ${fieldName};`);
    accessors.push(getterSetter(ref.referencedPkJavaType, fieldName));
  }

  const manyRefs = allManyRefs(klass);
  if (manyRefs.length) imports.push('java.util.List');
  for (const ref of manyRefs) {
    if (ref.referencedPkJavaImport) imports.push(ref.referencedPkJavaImport);
    const fieldName = `${ref.fieldName}Ids`;
    fields.push(`    private List<${ref.referencedPkJavaType}> ${fieldName};`);
    accessors.push(getterSetter(`List<${ref.referencedPkJavaType}>`, fieldName));
  }

  if (usesNotNull) imports.push('jakarta.validation.constraints.NotNull');

  return `${generatedFileHeader(`DTO de entrada de "${klass.className}".`)}
package ${model.packageName}.dto;

${importLines(imports)}
public class ${klass.className}RequestDTO {

${fields.join('\n\n')}

${accessors.join('\n\n')}
}
`;
}

export function renderResponseDto(model: GenerationModel, klass: GenClass): string {
  const imports: string[] = [];
  const pk = klass.pkAttribute;
  if (pk.javaImport) imports.push(pk.javaImport);

  const fields: string[] = [`    private ${pk.javaType} id;`];
  const accessors: string[] = [getterSetter(pk.javaType, 'id')];

  for (const attr of allAttributes(klass)) {
    if (attr.javaImport) imports.push(attr.javaImport);
    fields.push(`    private ${attr.javaType} ${attr.fieldName};`);
    accessors.push(getterSetter(attr.javaType, attr.fieldName));
  }

  for (const ref of allSingleRefs(klass)) {
    if (ref.referencedPkJavaImport) imports.push(ref.referencedPkJavaImport);
    const fieldName = `${ref.fieldName}Id`;
    fields.push(`    private ${ref.referencedPkJavaType} ${fieldName};`);
    accessors.push(getterSetter(ref.referencedPkJavaType, fieldName));
  }

  const manyRefs = allManyRefs(klass);
  if (manyRefs.length) imports.push('java.util.List');
  for (const ref of manyRefs) {
    if (ref.referencedPkJavaImport) imports.push(ref.referencedPkJavaImport);
    const fieldName = `${ref.fieldName}Ids`;
    fields.push(`    private List<${ref.referencedPkJavaType}> ${fieldName};`);
    accessors.push(getterSetter(`List<${ref.referencedPkJavaType}>`, fieldName));
  }

  return `${generatedFileHeader(`DTO de salida de "${klass.className}".`)}
package ${model.packageName}.dto;

${importLines(imports)}
public class ${klass.className}ResponseDTO {

${fields.join('\n')}

${accessors.join('\n\n')}
}
`;
}
