import { GenClass, GenerationModel } from '../GenerationModel';
import { javaSqlName } from '../naming';
import { isAutoGeneratedPk } from '../typeMapping';
import { generatedFileHeader, getterSetter, importLines } from './javaUtil';

function generatedValueAnnotation(javaType: string): string {
  if (!isAutoGeneratedPk(javaType)) return '';
  if (javaType === 'UUID') {
    return '    @GeneratedValue(strategy = GenerationType.UUID)\n';
  }
  return '    @GeneratedValue(strategy = GenerationType.IDENTITY)\n';
}

export function renderEntity(model: GenerationModel, klass: GenClass): string {
  const imports: string[] = [];
  const isSubclass = Boolean(klass.parentClassName);
  const fields: string[] = [];
  const accessors: string[] = [];

  if (!isSubclass) {
    const pk = klass.pkAttribute;
    if (pk.javaImport) imports.push(pk.javaImport);
    fields.push(
      `    @Id\n${generatedValueAnnotation(pk.javaType)}    @Column(name = "${javaSqlName(pk.columnName)}")\n    private ${pk.javaType} ${pk.fieldName};`,
    );
    accessors.push(getterSetter(pk.javaType, pk.fieldName));
  }

  for (const attr of klass.attributes) {
    if (attr.javaImport) imports.push(attr.javaImport);
    fields.push(`    @Column(name = "${javaSqlName(attr.columnName)}", nullable = ${attr.nullable})\n    private ${attr.javaType} ${attr.fieldName};`);
    accessors.push(getterSetter(attr.javaType, attr.fieldName));
  }

  for (const ref of klass.singleRefs) {
    const joinColumn = [`name = "${javaSqlName(ref.columnName)}"`];
    if (!ref.optional) joinColumn.push('nullable = false');
    if (ref.unique) joinColumn.push('unique = true');
    fields.push(
      `    @${ref.annotation}${ref.optional ? '' : '(optional = false)'}\n` +
        `    @JoinColumn(${joinColumn.join(', ')})\n` +
        `    private ${ref.referencedClassName} ${ref.fieldName};`,
    );
    accessors.push(getterSetter(ref.referencedClassName, ref.fieldName));
  }

  if (klass.manyRefs.length > 0 || klass.composedCollections.length > 0) {
    imports.push('java.util.List', 'java.util.ArrayList');
  }

  for (const ref of klass.manyRefs) {
    fields.push(
      `    @ManyToMany\n` +
        `    @JoinTable(\n` +
        `        name = "${javaSqlName(ref.joinTableName)}",\n` +
        `        joinColumns = @JoinColumn(name = "${javaSqlName(ref.joinColumnName)}"),\n` +
        `        inverseJoinColumns = @JoinColumn(name = "${javaSqlName(ref.inverseJoinColumnName)}")\n` +
        `    )\n` +
        `    private List<${ref.referencedClassName}> ${ref.fieldName} = new ArrayList<>();`,
    );
    accessors.push(getterSetter(`List<${ref.referencedClassName}>`, ref.fieldName));
  }

  // Composicion: el todo es duenio del ciclo de vida de sus partes. Solo
  // getter: reemplazar la lista entera rompe orphanRemoval en Hibernate.
  for (const collection of klass.composedCollections) {
    fields.push(
      `    @OneToMany(mappedBy = "${collection.mappedBy}", cascade = CascadeType.ALL, orphanRemoval = true)\n` +
        `    private List<${collection.partClassName}> ${collection.fieldName} = new ArrayList<>();`,
    );
    accessors.push(getterSetter(`List<${collection.partClassName}>`, collection.fieldName, { setter: false }));
  }

  const classAnnotations = [`@Entity`, `@Table(name = "${javaSqlName(klass.tableName)}")`];
  if (klass.isInheritanceRoot) classAnnotations.push('@Inheritance(strategy = InheritanceType.JOINED)');
  if (isSubclass) classAnnotations.push(`@PrimaryKeyJoinColumn(name = "${javaSqlName(klass.pkAttribute.columnName)}")`);

  const description = isSubclass
    ? `Entidad JPA de la clase UML "${klass.className}" (hereda de ${klass.parentClassName}).`
    : `Entidad JPA de la clase UML "${klass.className}".`;

  return `${generatedFileHeader(description)}
package ${model.packageName}.model;

import jakarta.persistence.*;
${importLines(imports)}
${classAnnotations.join('\n')}
public class ${klass.className}${isSubclass ? ` extends ${klass.parentClassName}` : ''} {

${fields.join('\n\n')}

    public ${klass.className}() {
    }

${accessors.join('\n\n')}
}
`;
}
