import { allAttributes, allManyRefs, allSingleRefs, GenAttribute, GenClass, GenerationModel } from '../GenerationModel';
import { isAutoGeneratedPk } from '../typeMapping';

// Coleccion de Postman (formato v2.1) con el CRUD de cada entidad listo para
// probar: se importa en Postman y se ejecuta con el Runner de punta a punta.
//
// - Las carpetas van en orden de dependencias (una clase que necesita la FK
//   de otra se crea despues), y cada POST guarda el id devuelto en una
//   variable de la coleccion ({{productoId}}) que usan los requests siguientes.
// - Los DELETE van al final en orden inverso, para no borrar un registro que
//   otro todavia referencia (eso devolveria 409).

function idVariable(className: string): string {
  return `${className.charAt(0).toLowerCase()}${className.slice(1)}Id`;
}

// Los ids numericos van sin comillas en el JSON; los de texto/UUID, con.
function isNumericType(javaType: string): boolean {
  return ['Long', 'Integer', 'Double', 'BigDecimal'].includes(javaType);
}

function placeholder(variable: string, javaType: string): string {
  return isNumericType(javaType) ? `{{${variable}}}` : `"{{${variable}}}"`;
}

function sampleValue(attr: GenAttribute, edited: boolean): string {
  switch (attr.javaType) {
    case 'String':
      return JSON.stringify(`${attr.fieldName} ${edited ? 'editado' : 'de ejemplo'}`);
    case 'Integer':
    case 'Long':
      return edited ? '2' : '1';
    case 'Double':
      return edited ? '20.5' : '10.5';
    case 'BigDecimal':
      return edited ? '150.75' : '100.50';
    case 'Boolean':
      return edited ? 'false' : 'true';
    case 'LocalDate':
      return edited ? '"2026-02-20"' : '"2026-01-15"';
    case 'LocalDateTime':
      return edited ? '"2026-02-20T16:45:00"' : '"2026-01-15T10:30:00"';
    case 'UUID':
      return '"{{$guid}}"';
    default:
      return 'null';
  }
}

// PK asignada a mano (no autogenerada): se manda en el POST como "id".
function manualPkValue(pk: GenAttribute): string {
  switch (pk.javaType) {
    case 'String':
      return '"ID-{{$timestamp}}{{$randomInt}}"';
    case 'Double':
    case 'BigDecimal':
      return '{{$timestamp}}';
    default:
      return sampleValue(pk, false);
  }
}

// Orden de creacion: cada clase va despues de las clases a las que apunta
// por FK. Si hay un ciclo (dos clases que se apuntan entre si), se corta por
// una referencia opcional y esa FK queda en null en el ejemplo.
function creationOrder(model: GenerationModel): GenClass[] {
  const byName = new Map(model.classes.map((k) => [k.className, k]));
  const pending = [...model.classes];
  const ordered: GenClass[] = [];
  const placed = new Set<string>();

  const dependencies = (klass: GenClass, onlyRequired: boolean) =>
    allSingleRefs(klass)
      .filter((r) => r.referencedClassName !== klass.className && byName.has(r.referencedClassName))
      .filter((r) => !onlyRequired || !r.optional)
      .map((r) => r.referencedClassName);

  while (pending.length > 0) {
    let index = pending.findIndex((k) => dependencies(k, false).every((d) => placed.has(d)));
    if (index === -1) index = pending.findIndex((k) => dependencies(k, true).every((d) => placed.has(d)));
    if (index === -1) index = 0;
    const [next] = pending.splice(index, 1);
    ordered.push(next);
    placed.add(next.className);
  }
  return ordered;
}

function buildBody(klass: GenClass, created: Set<string>, edited: boolean): string {
  const lines: string[] = [];
  const pk = klass.pkAttribute;
  if (!isAutoGeneratedPk(pk.javaType)) {
    // El RequestDTO exige "id" (@NotNull) tambien en el PUT.
    lines.push(`"id": ${edited ? placeholder(idVariable(klass.className), pk.javaType) : manualPkValue(pk)}`);
  }
  for (const attr of allAttributes(klass)) {
    lines.push(`${JSON.stringify(attr.fieldName)}: ${sampleValue(attr, edited)}`);
  }
  for (const ref of allSingleRefs(klass)) {
    const value = created.has(ref.referencedClassName)
      ? placeholder(idVariable(ref.referencedClassName), ref.referencedPkJavaType)
      : 'null';
    lines.push(`"${ref.fieldName}Id": ${value}`);
  }
  for (const ref of allManyRefs(klass)) {
    const usable = created.has(ref.referencedClassName) && ref.referencedClassName !== klass.className;
    const value = usable ? `[${placeholder(idVariable(ref.referencedClassName), ref.referencedPkJavaType)}]` : '[]';
    lines.push(`"${ref.fieldName}Ids": ${value}`);
  }
  return `{\n${lines.map((l) => `  ${l}`).join(',\n')}\n}`;
}

interface PostmanRequest {
  name: string;
  request: {
    method: string;
    header: { key: string; value: string }[];
    url: { raw: string; host: string[]; path: string[] };
    body?: { mode: 'raw'; raw: string; options: { raw: { language: 'json' } } };
  };
  event: { listen: 'test'; script: { type: 'text/javascript'; exec: string[] } }[];
}

function request(
  name: string,
  method: string,
  pathSegments: string[],
  expectedStatus: number,
  body?: string,
  extraTest: string[] = [],
): PostmanRequest {
  return {
    name,
    request: {
      method,
      header: body ? [{ key: 'Content-Type', value: 'application/json' }] : [],
      url: { raw: `{{baseUrl}}/${pathSegments.join('/')}`, host: ['{{baseUrl}}'], path: pathSegments },
      ...(body ? { body: { mode: 'raw' as const, raw: body, options: { raw: { language: 'json' as const } } } } : {}),
    },
    event: [
      {
        listen: 'test',
        script: {
          type: 'text/javascript',
          exec: [`pm.test("Status ${expectedStatus}", () => pm.response.to.have.status(${expectedStatus}));`, ...extraTest],
        },
      },
    ],
  };
}

export function renderPostmanCollection(
  model: GenerationModel,
  options: { artifactId: string; port: number },
): string {
  const ordered = creationOrder(model);
  const created = new Set<string>();

  const entityFolders = ordered.map((klass) => {
    const slug = klass.pluralSlug;
    const variable = idVariable(klass.className);
    const createBody = buildBody(klass, created, false);
    created.add(klass.className);
    const updateBody = buildBody(klass, created, true);
    const inheritance = klass.parentClassName ? ` (hereda de ${klass.parentClassName})` : '';

    return {
      name: `${klass.className}${inheritance}`,
      item: [
        request(`Crear ${klass.className}`, 'POST', [slug], 201, createBody, [
          'const body = pm.response.json();',
          `if (body && body.id !== undefined) pm.collectionVariables.set("${variable}", body.id);`,
        ]),
        request(`Listar ${klass.className}`, 'GET', [slug], 200, undefined, [
          'pm.test("Devuelve una lista", () => pm.expect(pm.response.json()).to.be.an("array"));',
        ]),
        request(`Obtener ${klass.className} por id`, 'GET', [slug, `{{${variable}}}`], 200),
        request(`Actualizar ${klass.className}`, 'PUT', [slug, `{{${variable}}}`], 200, updateBody),
      ],
    };
  });

  const deleteFolder = {
    name: 'Eliminar (orden inverso)',
    item: [...ordered]
      .reverse()
      .map((klass) =>
        request(`Eliminar ${klass.className}`, 'DELETE', [klass.pluralSlug, `{{${idVariable(klass.className)}}}`], 204),
      ),
  };

  const first = ordered[0];
  // El 400 solo se puede demostrar en una clase que tenga algo obligatorio.
  const withRequired = ordered.find(
    (k) =>
      !isAutoGeneratedPk(k.pkAttribute.javaType) ||
      allAttributes(k).some((a) => !a.nullable) ||
      allSingleRefs(k).some((r) => !r.optional),
  );
  const errorFolder = first
    ? {
        name: 'Casos de error',
        item: [
          request(`${first.className} inexistente (404)`, 'GET', [first.pluralSlug, '999999'], 404),
          ...(withRequired
            ? [request(`${withRequired.className} sin datos obligatorios (400)`, 'POST', [withRequired.pluralSlug], 400, '{}')]
            : []),
        ],
      }
    : null;

  const collection = {
    info: {
      name: options.artifactId,
      description:
        'CRUD generado por CASE_UML. Ejecutar la coleccion completa con el Runner: crea los registros en orden ' +
        'de dependencias, guarda los ids devueltos y al final los elimina en orden inverso.',
      schema: 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json',
    },
    variable: [
      { key: 'baseUrl', value: `http://localhost:${options.port}/api` },
      ...ordered.map((klass) => ({ key: idVariable(klass.className), value: '' })),
    ],
    item: [...entityFolders, ...(errorFolder ? [errorFolder] : []), deleteFolder],
  };

  return `${JSON.stringify(collection, null, 2)}\n`;
}
