import { allAttributes, allManyRefs, allSingleRefs, GenClass, GenerationModel } from '../GenerationModel';
import { isAutoGeneratedPk } from '../typeMapping';
import { capitalize, generatedFileHeader, importLines, lowerFirst } from './javaUtil';

export function renderService(model: GenerationModel, klass: GenClass): string {
  const singleRefs = allSingleRefs(klass);
  const manyRefs = allManyRefs(klass);
  const pk = klass.pkAttribute;

  // Repositorio a usar para resolver una referencia por id: el propio si es
  // una autorrelacion, o el de la otra clase (inyectado por constructor).
  const repoVar = (className: string) => (className === klass.className ? 'repository' : `${lowerFirst(className)}Repository`);
  const referencedClassNames = Array.from(
    new Set([...singleRefs, ...manyRefs].map((r) => r.referencedClassName).filter((name) => name !== klass.className)),
  );

  const imports = [
    `${model.packageName}.model.${klass.className}`,
    `${model.packageName}.repository.${klass.className}Repository`,
    `${model.packageName}.dto.${klass.className}RequestDTO`,
    `${model.packageName}.dto.${klass.className}ResponseDTO`,
    'org.springframework.http.HttpStatus',
    'org.springframework.stereotype.Service',
    'org.springframework.transaction.annotation.Transactional',
    'org.springframework.web.server.ResponseStatusException',
    'java.util.List',
    'java.util.stream.Collectors',
  ];
  if (pk.javaImport) imports.push(pk.javaImport);
  for (const name of referencedClassNames) {
    imports.push(`${model.packageName}.repository.${name}Repository`);
  }
  if (manyRefs.length) {
    imports.push('java.util.ArrayList', 'java.util.HashSet');
    for (const ref of manyRefs) imports.push(`${model.packageName}.model.${ref.referencedClassName}`);
  }

  const repoFields = [`    private final ${klass.className}Repository repository;`];
  const ctorParams = [`${klass.className}Repository repository`];
  const ctorAssignments = ['        this.repository = repository;'];
  for (const name of referencedClassNames) {
    repoFields.push(`    private final ${name}Repository ${repoVar(name)};`);
    ctorParams.push(`${name}Repository ${repoVar(name)}`);
    ctorAssignments.push(`        this.${repoVar(name)} = ${repoVar(name)};`);
  }

  const applyLines: string[] = [];
  for (const attr of allAttributes(klass)) {
    applyLines.push(`        entity.set${capitalize(attr.fieldName)}(dto.get${capitalize(attr.fieldName)}());`);
  }
  for (const ref of singleRefs) {
    const idGetter = `dto.get${capitalize(ref.fieldName)}Id()`;
    applyLines.push(
      `        entity.set${capitalize(ref.fieldName)}(${idGetter} == null ? null : ${repoVar(ref.referencedClassName)}.findById(${idGetter})\n` +
        `            .orElseThrow(() -> new ResponseStatusException(HttpStatus.BAD_REQUEST, "${ref.referencedClassName} no encontrado: " + ${idGetter})));`,
    );
  }
  for (const ref of manyRefs) {
    const idsGetter = `dto.get${capitalize(ref.fieldName)}Ids()`;
    applyLines.push(
      `        if (${idsGetter} != null) {\n` +
        `            List<${ref.referencedClassName}> ${ref.fieldName} = ${repoVar(ref.referencedClassName)}.findAllById(${idsGetter});\n` +
        `            if (${ref.fieldName}.size() != new HashSet<>(${idsGetter}).size()) {\n` +
        `                throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Algun ${ref.referencedClassName} indicado no existe");\n` +
        `            }\n` +
        `            entity.set${capitalize(ref.fieldName)}(new ArrayList<>(${ref.fieldName}));\n` +
        `        }`,
    );
  }

  const responseLines: string[] = [`        dto.setId(entity.get${capitalize(pk.fieldName)}());`];
  for (const attr of allAttributes(klass)) {
    responseLines.push(`        dto.set${capitalize(attr.fieldName)}(entity.get${capitalize(attr.fieldName)}());`);
  }
  for (const ref of singleRefs) {
    const getter = `entity.get${capitalize(ref.fieldName)}()`;
    responseLines.push(
      `        dto.set${capitalize(ref.fieldName)}Id(${getter} != null ? ${getter}.get${capitalize(ref.referencedPkFieldName)}() : null);`,
    );
  }
  for (const ref of manyRefs) {
    responseLines.push(
      `        dto.set${capitalize(ref.fieldName)}Ids(entity.get${capitalize(ref.fieldName)}().stream()\n` +
        `            .map(${ref.referencedClassName}::get${capitalize(ref.referencedPkFieldName)})\n` +
        `            .collect(Collectors.toList()));`,
    );
  }

  // Si la PK no la autogenera la base (String, fechas...), la manda el
  // cliente: se asigna a mano y se evita pisar un registro existente.
  const pkAssignment = isAutoGeneratedPk(pk.javaType)
    ? ''
    : `        if (repository.existsById(dto.getId())) {\n` +
      `            throw new ResponseStatusException(HttpStatus.CONFLICT, "Ya existe ${klass.className} con id: " + dto.getId());\n` +
      `        }\n` +
      `        entity.set${capitalize(pk.fieldName)}(dto.getId());\n`;

  const notFound = `new ResponseStatusException(HttpStatus.NOT_FOUND, "${klass.className} no encontrado: " + id)`;

  return `${generatedFileHeader(`Servicio de "${klass.className}": CRUD basico (seccion 33).`)}
package ${model.packageName}.service;

${importLines(imports)}
@Service
public class ${klass.className}Service {

${repoFields.join('\n')}

    public ${klass.className}Service(${ctorParams.join(', ')}) {
${ctorAssignments.join('\n')}
    }

    @Transactional(readOnly = true)
    public List<${klass.className}ResponseDTO> findAll() {
        return repository.findAll().stream().map(this::toResponseDTO).collect(Collectors.toList());
    }

    @Transactional(readOnly = true)
    public ${klass.className}ResponseDTO findById(${pk.javaType} id) {
        ${klass.className} entity = repository.findById(id).orElseThrow(() -> ${notFound});
        return toResponseDTO(entity);
    }

    @Transactional
    public ${klass.className}ResponseDTO create(${klass.className}RequestDTO dto) {
        ${klass.className} entity = new ${klass.className}();
${pkAssignment}        applyDto(entity, dto);
        return toResponseDTO(repository.save(entity));
    }

    @Transactional
    public ${klass.className}ResponseDTO update(${pk.javaType} id, ${klass.className}RequestDTO dto) {
        ${klass.className} entity = repository.findById(id).orElseThrow(() -> ${notFound});
        applyDto(entity, dto);
        return toResponseDTO(repository.save(entity));
    }

    @Transactional
    public void delete(${pk.javaType} id) {
        ${klass.className} entity = repository.findById(id).orElseThrow(() -> ${notFound});
        repository.delete(entity);
    }

    private void applyDto(${klass.className} entity, ${klass.className}RequestDTO dto) {
${applyLines.join('\n')}
    }

    private ${klass.className}ResponseDTO toResponseDTO(${klass.className} entity) {
        ${klass.className}ResponseDTO dto = new ${klass.className}ResponseDTO();
${responseLines.join('\n')}
        return dto;
    }
}
`;
}
